### ISSUE TITLE
html 二级目录支持吗？

### ISSUE THREAD

**Issue by yangchaojiang** [lfyfly/webpack-multi-page#1]
如题。
一个项目功能比较多很多通过目录形式分开

**Comment by lfyfly** [comment]
暂不支持

**Comment by yangchaojiang** [comment]
哦哦哦

**Comment by lfyfly** [comment]
`webpack-multi-page@1.1`pages多级目录支持（忽略下划线开头的文件和文件夹）
  - 当配置文件`webpack.cfg.js`中`build.assetsPublicPath === './' `，二级目录以上页面需要在页面中，增加`<base>`标签进行修正相对路径。如`src/pages/test/test-0.html`中的`<head>`中的`<base href="../" />`
  - 当配置文件`webpack.cfg.js`中`build.assetsPublicPath === '/' `, 则路径为绝对路径，无需修正路径

**Comment by yangchaojiang** [comment]
哦哦哦谢谢了
