### ISSUE TITLE
支持全局引用吗

### ISSUE THREAD

**Issue by yangchaojiang** [lfyfly/webpack-multi-page#2]
例如每个页面都需要vue
在每一个 .js文件引用vue ，重复
能不能有一个地方全局引用，在build时候的制自动导入

**Comment by lfyfly** [comment]
建议手动引入，明确依赖关系

**Comment by yangchaojiang** [comment]
哦哦哦。谢谢了。 还有一个问题就是css的文件。可以放在static的css的目录下吗？

**Comment by lfyfly** [comment]
可以啊
```
<link rel="stylesheet" href="static/css/static.css">
```

**Comment by yangchaojiang** [comment]
npm run build 生成的css的图片就不对了
![default](https://user-images.githubusercontent.com/13806413/43749001-e9805e7a-9a24-11e8-8ba9-9f9df3abf6e7.png)
测试网页
![default](https://user-images.githubusercontent.com/13806413/43749180-95c22ce0-9a25-11e8-8341-d43d93bc035a.png)

**Comment by lfyfly** [comment]
我的css打包明明在`dist`根目录下，你怎么在css目录下

**Comment by yangchaojiang** [comment]
![default](https://user-images.githubusercontent.com/13806413/43749790-21a6d286-9a28-11e8-8891-4292fea37e36.png)
我该这里的

**Comment by lfyfly** [comment]
为了html和css

**Comment by yangchaojiang** [comment]
为了规范些:sob::sob::sob:

**Comment by lfyfly** [comment]
为了html和css的图片资源相对路径可以准确，才将css文件打包在`dist`目录下。
如果你是全绝对路径，那就无所谓了
`readme`中已经写了

**Comment by yangchaojiang** [comment]
生成css文件里央视的 背景图片的路径了:sob::sob:

**Comment by lfyfly** [comment]
打包到css文件夹中，你可以手动修正css中的图片路径。不过有时可能会忘记，然后打包上线，然后你懂的。

**Comment by yangchaojiang** [comment]
哦哦哦。好吧。:joy::joy::joy:

**Comment by lfyfly** [comment]
hello，打包到`dist/static/css`我找到解决的方法了,我已经在@1.1.1更新了
主要修改`webpack.prod.js`两个地方
```
 rules: [
        {
          test: /\.(css|scss|sass)$/,
          use: ExtractTextPlugin.extract({
            fallback: "style-loader",
            use: styleLoader,
            publicPath:'../../' // 新增此行，css图片路径修正成`../../static/img/xxx.jpg`
          })
        },
      ]
```
```
 new ExtractTextPlugin({
        filename: `${cfg.build.assetsSubDirectory}/css/[name].[md5:contenthash:hex:20].css`,
      }),
```

**Comment by yangchaojiang** [comment]
谢谢了/完美:grin::grin::grin:
