### ISSUE TITLE
manifest.js

### ISSUE THREAD

**Issue by J-env** [lfyfly/webpack-multi-page#3]
我想问下 manifest.js 是做什么的啊？

**Comment by lfyfly** [comment]
`optimization.runtimeChunk`配置项生成，我看文档也没懂，下面的是位慕课网老师的回答

 https://coding.imooc.com/learn/questiondetail/51202.html

**Comment by J-env** [comment]
@lfyfly 
OK，

我发现global.scss的样式会生成到每个页面的css里面，并不是独立出来一个commons.css （这样的话不够友好， 里面只能使用scss变量）

**Comment by lfyfly** [comment]
- @1.2.0 新增页面共有css文件入口支持
```
commonCss:{
    entry: path.resolve(__dirname,'src/common_css_entry.js'), // String 必填，入口文件，绝对地址
    exclude:['about'] // Arrary 排除页面，不填所有页面都引入common_css
    // ['about'] 代表about页面不引用 common_css
  },
```
